### ISSUE TITLE
how Run & readme

### ISSUE THREAD

**Issue by Al13n0** [gnosis/pydkg#3]
Hey I would like to use your algorithm.
I dont  undestand how could i run the code? 
Maybe update the README with more information will be usefull also for other people.

**Comment by cag** [comment]
Hey, thank you for your interest!

Unfortunately, this project is getting retired, so I don't want you to invest your time in this if there is no maintainer. In the meantime, might I suggest looking into Parity's [Secret Store](https://wiki.parity.io/Secret-Store-Configuration.html)? We also will have an implementation of DKG, but it will written in Go.
